version: '3.5'
networks:
  ffmpeg-network:
    name: ffmpeg-network
services:
  nginx:
    build: nginx
    restart: always
    links:
      - apiserver
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - ffmpeg-network
  apiserver:
    build: apiserver
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - ffmpeg-network
# uncomment next line to enable Swagger UI on port localhost:5000
#   ports:
#     - "8080:5000"
    environment:
      - SUPERVISOR_INTERVAL=5
      - STOP_AFTER_SECONDS=300
